global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'weather_consumer'
    static_configs: 
      - targets: ['weather_consumer:8000']
  
  - job_name: 'weather_producer'
    static_configs:
      - targets: ['weather_pipeline:8001']
  
  - job_name: 'weather_fetcher'
    static_configs: 
      - targets: ['weather_fetcher:8002']